  name: MyMCMMOPet
  main: io.github.takato65.mymcmmopet.MyMCMMOPet
  version: 1.2
  depend: [mcMMO, MyPet]
  api-version: 1.16
  commands:
    mmopet:
      description: mmopet config command
      usage: /<command>
      permission: mymcmmopet.mmopet

  permissions:
    mymcmmopet.*:
      description: mmopet config permissions
      default: op
